import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Treelab app</title>
        <meta name="description" content="Generated by Treelab app next template" />
        <link rel="icon" href="/favicon-light.ico" />
      </Head>
    </div>
  );
};

export default Home;
